from rdflib import Graph, compare
import os.path

# Script to check whether the output generated by `cl-ttl-parser` is graph
# equivalent to the expected result as defined part of the RDF test suite.
# This script parses the manifest file for RDF 1.1 turtle tests and for each
# test of type `TestTurtleEval`:
# - check whether a `cl-ttl-parser` output file can be found (these should be
#   automatically created when running `(cl-ttl-parser-tests::run-all-tests)`
#   in a lisp REPL.)
# - check whether the contents of the create output file is graph equivalent
#   with the contents of the result file for that test as specified in the
#   manifest file.

manifest = Graph()
manifest.parse("rdf-tests/rdf/rdf11/rdf-turtle/manifest.ttl")

test_names_query = """
PREFIX mf: <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdft: <http://www.w3.org/ns/rdftest#>

SELECT DISTINCT ?name ?result
WHERE {
  ?uri a rdft:TestTurtleEval ;
       mf:name ?name ;
       mf:result ?result .
}"""

test_names = manifest.query(test_names_query)

failed_tests = {}
missing_result = []

for test in test_names:
    name, result_file = test

    expected = Graph()
    expected.parse(result_file)

    parsed_path = "./output-files/" + name + ".nt"
    if os.path.isfile(parsed_path):
        parsed = Graph()
        try:
            parsed.parse(parsed_path)

            equal = compare.to_isomorphic(expected) == compare.to_isomorphic(parsed)
            if equal:
                print(f"[PASS] {name}")
            else:
                failed_tests[name] = "graphs are NOT equal"
                print(f"[FAIL] {name}: graphs are NOT equal")
        except Exception as e:
            failed_tests[name] = f"{e}"
            print(f'[FAIL] {name}: Could not parse file due to exception: "{e}"')

    else:
        missing_result.append(name)
        print(f"[FAIL] {name}: no parsed result found")


print("\nSummary:")

print("\tMissing parsed result file:")
for name in missing_result:
    print("\t  " + name)
print(f"\tNumber of missing result files: {len(missing_result)}\n")

print("\tFailed tests:")
for name, reason in failed_tests.items():
    print(f"\t  {name}: {reason}")
print(f"\tNumber of failed tests: {len(failed_tests)}")
